# Generated by Django 5.1.1 on 2025-02-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("superadmin", "Super Admin"),
                    ("data_analyst", "Data Analyst"),
                    ("drone_controller", "Drone Controller"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Role",
        ),
    ]
