# Generated by Django 5.1.6 on 2025-05-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_emailotp_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("admin", "Admin"),
                    ("superadmin", "Super Admin"),
                    ("data_analyst", "Data Analyst"),
                    ("drone_controller", "Drone Controller"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
