# Generated by Django 5.2 on 2025-05-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_customuser_status_alter_customuser_role"),
        ("authentication", "0007_customuser_profile_image"),
    ]

    operations = []
