# Generated by Django 5.2 on 2025-05-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_customuser_user'),
        ('authentication', '0008_merge_20250523_2003'),
    ]

    operations = [
    ]
