# Generated by Django 5.1.6 on 2025-04-30 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0005_alter_emailotp_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PowerPlant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("total_tasks", models.IntegerField()),
                ("createdAt", models.DateField(auto_now_add=True)),
                ("updatedAt", models.DateField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "admin",
                    models.ManyToManyField(
                        related_name="admins", to="authentication.customuser"
                    ),
                ),
                (
                    "data_analyst",
                    models.ManyToManyField(
                        related_name="data_analysts", to="authentication.customuser"
                    ),
                ),
                (
                    "drone_controller",
                    models.ManyToManyField(
                        related_name="drone_controllers", to="authentication.customuser"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateField(auto_now_add=True)),
                ("updatedAt", models.DateField(auto_now=True)),
                ("energy_generated", models.FloatField()),
                (
                    "powerplant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="myadmin.powerplant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                (
                    "powerplant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zone",
                        to="myadmin.powerplant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolarCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solar_cell",
                        to="myadmin.zone",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("efficiency_percentage", models.FloatField()),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="myadmin.report",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="myadmin.zone",
                    ),
                ),
            ],
        ),
    ]
