# Generated by Django 5.2 on 2025-05-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarcell',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='solarcell_images/'),
        ),
    ]
