# Generated by Django 5.1.6 on 2025-05-09 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_solarcell_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('powerplant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.powerplant')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.zone')),
            ],
        ),
    ]
