# Generated by Django 5.1.6 on 2025-05-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_remove_reportresult_zone_reportresult_solar_cell_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarcell',
            name='x_zposition',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solarcell',
            name='y_position',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
