# Generated by Django 5.1.6 on 2025-05-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_reportresult_zone_alter_reportresult_solar_cell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solarcell',
            old_name='x_zposition',
            new_name='x_position',
        ),
        migrations.AlterField(
            model_name='zone',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='zone',
            name='width',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='solarcell',
            constraint=models.UniqueConstraint(fields=('zone', 'x_position', 'y_position'), name='unique_solarcell_position_per_zone'),
        ),
    ]
