# Generated by Django 5.2 on 2025-05-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_imageupload'),
        ('myadmin', '0005_rename_x_zposition_solarcell_x_position_and_more'),
    ]

    operations = [
    ]
