# Generated by Django 5.2 on 2025-05-10 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_merge_20250509_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarcell',
            name='image',
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='powerplant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.powerplant'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.zone'),
        ),
    ]
