# Generated by Django 5.2 on 2025-05-10 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_remove_solarcell_image_alter_imageupload_powerplant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportresult',
            name='efficiency_percentage',
        ),
        migrations.CreateModel(
            name='CellEfficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efficiency_percentage', models.FloatField()),
                ('report_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_efficiency', to='myadmin.reportresult')),
                ('solar_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_efficiency', to='myadmin.solarcell')),
            ],
        ),
    ]
