# Generated by Django 5.2 on 2025-05-10 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0008_remove_reportresult_efficiency_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportresult',
            name='solar_cell',
        ),
    ]
