# Generated by Django 5.2 on 2025-05-23 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_customuser_profile_image'),
        ('myadmin', '0009_remove_reportresult_solar_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.customuser'),
            preserve_default=False,
        ),
    ]
